### ISSUE TITLE
Build failure in 2.4.1

### ISSUE THREAD

**Issue by GaryElshaw** [Lymphatus/caesium-image-compressor#214]
Build failure in main.cpp.o

Caesium Image Compressor 2.4.1

OS: Manjaro
Version: Linux 6.2.16-2-MANJARO

1. Follow build instructions

**Application Log**
Build output: [caesium.txt](https://github.com/Lymphatus/caesium-image-compressor/files/11845929/caesium.txt)

**Comment by Lymphatus** [comment]
Which Qt version are you using? Caesium v2.4.1 works on Qt 6.5.x.

`colorScheme` is new to Qt 6.5, so that might be the issue.
`/home/gary/Downloads/caesium-image-compressor-2.4.1/src/main.cpp:34:41: error: ‘class QStyleHints’ has no member named ‘colorScheme’`

**Comment by GaryElshaw** [comment]
It's a bit weird, eh? I'm using qt6-base-6.5.0-3

**Comment by Lymphatus** [comment]
My guess is that some components of the Qt Framework are missing from that package, but it's hard to tell which. From my experience with compiling the project in Manjaro, I ended up using the Qt Installer from their website instead of pacman. I think that might solve the issue.

PS: also remember to install Qt ImageFormats plugin

**Comment by GaryElshaw** [comment]
I double-checked ImageFormats was there; and decided to use the qt online installer. Still seeing the same error, but as an aside, also noted this.  

`cmake --build build_dir --config Release --target caesium_image_compressor
-- GLOB mismatch!
CMake Warning (dev) at /usr/share/cmake/Modules/GNUInstallDirs.cmake:243 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
`

**Comment by Lymphatus** [comment]
It happened to me when the CMAKE_PREFIX_PATH was still pointing to the old Qt version. Can it be your case?

**Comment by GaryElshaw** [comment]
This is the path i've been using: -DCMAKE_PREFIX_PATH=/usr/include/qt6

**Comment by Lymphatus** [comment]
My guess, but it's probably the one of the pacman install. The Qt installer usually installs all the files in the home directory, if you don't change it of course.
